apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service-mongo
  template:
    metadata:
      labels:
        app: email-service-mongo
    spec:
      containers:
        - name: email-service-mongo
          image: mongo
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: email-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: email-service-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
